var datas = {
	    "code": 10000,
	    "msg": "成功",
	    "result": {
	        "currentPage": 1,
	        "hasNextPage": true,
	        "hasPrePage": false,
	        "nextPage": 2,
	        "offset": 0,
	        "pageCount": 2,
	        "pageSize": 10,
	        "paraMap": null,
	        "prePage": 1,
	        "recordCount": 11,
	        "recordList": [
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440303,
	                "e_cityId": 440300,
	                "e_detail": "深圳市罗湖区",
	                "e_provinceId": 440000,
	                "goodsName": "永远",
	                "goodsType": 104,
	                "goodsTypeStr": "食品饮料",
	                "iconUrl": null,
	                "memberId": 277764,
	                "mileage": 3.28,
	                "mobile": "13710997321",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 18:00",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104428,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": 2,
	                "totalWeight": 2,
	                "userName": "盛HP"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 0,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440303,
	                "e_cityId": 440300,
	                "e_detail": "深圳市罗湖区",
	                "e_provinceId": 440000,
	                "goodsName": "急急急",
	                "goodsType": 105,
	                "goodsTypeStr": "冷冻商品",
	                "iconUrl": null,
	                "memberId": 281259,
	                "mileage": 0,
	                "mobile": "15993314706",
	                "nstRule": 2,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 17:45",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104427,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": 2,
	                "totalWeight": 1,
	                "userName": "康JQ"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 102,
	                "goodsTypeStr": "干调粮油",
	                "iconUrl": null,
	                "memberId": 281259,
	                "mileage": 0,
	                "mobile": "15993314706",
	                "nstRule": 2,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 16:45",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104426,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 777,
	                "userName": "康JQ"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440303,
	                "e_cityId": 440300,
	                "e_detail": "深圳市罗湖区",
	                "e_provinceId": 440000,
	                "goodsName": "大白菜",
	                "goodsType": 102,
	                "goodsTypeStr": "干调粮油",
	                "iconUrl": null,
	                "memberId": 277764,
	                "mileage": 0,
	                "mobile": "13710997321",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-11-03 07:00",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104425,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 1,
	                "userName": "盛HP"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 103,
	                "goodsTypeStr": "活鲜水产",
	                "iconUrl": null,
	                "memberId": 276072,
	                "mileage": 0,
	                "mobile": "15384474676",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 16:30",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104424,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 777,
	                "userName": "严GC"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 102,
	                "goodsTypeStr": "干调粮油",
	                "iconUrl": null,
	                "memberId": 276072,
	                "mileage": 0,
	                "mobile": "15384474676",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 16:15",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104423,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 666,
	                "userName": "严GC"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 105,
	                "goodsTypeStr": "冷冻商品",
	                "iconUrl": null,
	                "memberId": 281205,
	                "mileage": 0,
	                "mobile": "15949001556",
	                "nstRule": 2,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 15:45",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104421,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 444,
	                "userName": "罗PZ"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 105,
	                "goodsTypeStr": "冷冻商品",
	                "iconUrl": null,
	                "memberId": 276072,
	                "mileage": 0,
	                "mobile": "15384474676",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 16:45",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104420,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 333,
	                "userName": "严GC"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 108,
	                "goodsTypeStr": "日用品",
	                "iconUrl": null,
	                "memberId": 281205,
	                "mileage": 0,
	                "mobile": "15949001556",
	                "nstRule": 2,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 16:45",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104419,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 233,
	                "userName": "罗PZ"
	            },
	            {
	                "carLength": -1,
	                "carType": -1,
	                "carTypeStr": "不限",
	                "cerCompany": "待认证",
	                "cerCompanyStatus": 0,
	                "cerPersonal": "已认证",
	                "cerPersonalStatus": 2,
	                "createTime": "2016-11-16 13:45:36",
	                "e_areaId": 440305,
	                "e_cityId": 440300,
	                "e_detail": "深圳市南山区",
	                "e_provinceId": 440000,
	                "goodsName": null,
	                "goodsType": 105,
	                "goodsTypeStr": "冷冻商品",
	                "iconUrl": null,
	                "memberId": 276072,
	                "mileage": 0,
	                "mobile": "15384474676",
	                "nstRule": 1,
	                "s_areaId": 440304,
	                "s_cityId": 440300,
	                "s_detail": "深圳市福田区",
	                "s_provinceId": 440000,
	                "sendDate": "2016-10-28 15:30",
	                "sendGoodsType": 1,
	                "sendGoodsTypeStr": "不限",
	                "sourceId": 1104418,
	                "sourceType": 2,
	                "timeStr": "22小时前",
	                "totalSize": null,
	                "totalWeight": 3,
	                "userName": "严GC"
	            }
	        ]
	    },
	    "success": true
	}

var datilData = {
	    "code": 10000,
	    "msg": "成功",
	    "result": {
	        "carLength": -1,
	        "carType": -1,
	        "carTypeStr": "不限",
	        "cerPersonal": "已认证",
	        "cerPersonalStatus": 2,
	        "desFullAddr": null,
	        "e_detail": "深圳市南山区",
	        "e_detailed_address": "",
	        "freight": 0,
	        "goodsName": null,
	        "goodsSource": "物流公司推荐",
	        "goodsType": 102,
	        "goodsTypeStr": "干调粮油",
	        "iconUrl": null,
	        "memberId": 281259,
	        "mileage": 0,
	        "mobile": "15993314706",
	        "nstRule": 2,
	        "nstRuleStr": "代发",
	        "remark": null,
	        "s_detail": "深圳市福田区",
	        "s_detailed_address": "",
	        "sendDate": "2016-10-28 16:45",
	        "sendGoodsType": 1,
	        "sendGoodsTypeStr": "不限",
	        "shipperMobile": null,
	        "shipperName": null,
	        "sourceId": 1104426,
	        "sourceStatus": 1,
	        "sourceStatusStr": "已发布",
	        "sourceType": 2,
	        "srcFullAddr": null,
	        "totalSize": null,
	        "totalWeight": 777,
	        "userName": "康JQ"
	    },
	    "success": true
	}


var areaData = {
	    "code": 10000,
	    "msg": "成功",
	    "result": {
	        "directlyCity": [
	            {
	                "area": "北京市",
	                "areaID": "110000",
	                "areaType": "1",
	                "father": null,
	                "id": 1,
	                "isParent": false,
	                "lat": 39.929985,
	                "lng": 116.395645,
	                "parentName": null
	            },
	            {
	                "area": "天津市",
	                "areaID": "120000",
	                "areaType": "1",
	                "father": null,
	                "id": 2,
	                "isParent": false,
	                "lat": 39.14393,
	                "lng": 117.210815,
	                "parentName": null
	            },
	            {
	                "area": "上海市",
	                "areaID": "310000",
	                "areaType": "1",
	                "father": null,
	                "id": 9,
	                "isParent": false,
	                "lat": 31.24916,
	                "lng": 121.4879,
	                "parentName": null
	            },
	            {
	                "area": "重庆市",
	                "areaID": "500000",
	                "areaType": "1",
	                "father": null,
	                "id": 22,
	                "isParent": false,
	                "lat": 29.544605,
	                "lng": 106.53063,
	                "parentName": null
	            }
	        ],
	        "province": [
	            {
	                "area": "河北省",
	                "areaID": "130000",
	                "areaType": "1",
	                "father": null,
	                "id": 3,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "山西省",
	                "areaID": "140000",
	                "areaType": "1",
	                "father": null,
	                "id": 4,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "辽宁省",
	                "areaID": "210000",
	                "areaType": "1",
	                "father": null,
	                "id": 6,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "吉林省",
	                "areaID": "220000",
	                "areaType": "1",
	                "father": null,
	                "id": 7,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "黑龙江省",
	                "areaID": "230000",
	                "areaType": "1",
	                "father": null,
	                "id": 8,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "江苏省",
	                "areaID": "320000",
	                "areaType": "1",
	                "father": null,
	                "id": 10,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "浙江省",
	                "areaID": "330000",
	                "areaType": "1",
	                "father": null,
	                "id": 11,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "安徽省",
	                "areaID": "340000",
	                "areaType": "1",
	                "father": null,
	                "id": 12,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "福建省",
	                "areaID": "350000",
	                "areaType": "1",
	                "father": null,
	                "id": 13,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "江西省",
	                "areaID": "360000",
	                "areaType": "1",
	                "father": null,
	                "id": 14,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "山东省",
	                "areaID": "370000",
	                "areaType": "1",
	                "father": null,
	                "id": 15,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "河南省",
	                "areaID": "410000",
	                "areaType": "1",
	                "father": null,
	                "id": 16,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "湖北省",
	                "areaID": "420000",
	                "areaType": "1",
	                "father": null,
	                "id": 17,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "湖南省",
	                "areaID": "430000",
	                "areaType": "1",
	                "father": null,
	                "id": 18,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "广东省",
	                "areaID": "440000",
	                "areaType": "1",
	                "father": null,
	                "id": 19,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "海南省",
	                "areaID": "460000",
	                "areaType": "1",
	                "father": null,
	                "id": 21,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "四川省",
	                "areaID": "510000",
	                "areaType": "1",
	                "father": null,
	                "id": 23,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "贵州省",
	                "areaID": "520000",
	                "areaType": "1",
	                "father": null,
	                "id": 24,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "云南省",
	                "areaID": "530000",
	                "areaType": "1",
	                "father": null,
	                "id": 25,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "陕西省",
	                "areaID": "610000",
	                "areaType": "1",
	                "father": null,
	                "id": 27,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "甘肃省",
	                "areaID": "620000",
	                "areaType": "1",
	                "father": null,
	                "id": 28,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "青海省",
	                "areaID": "630000",
	                "areaType": "1",
	                "father": null,
	                "id": 29,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            }
	        ],
	        "region": [
	            {
	                "area": "内蒙古",
	                "areaID": "150000",
	                "areaType": "1",
	                "father": null,
	                "id": 5,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "广西",
	                "areaID": "450000",
	                "areaType": "1",
	                "father": null,
	                "id": 20,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "西藏",
	                "areaID": "540000",
	                "areaType": "1",
	                "father": null,
	                "id": 26,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "宁夏",
	                "areaID": "640000",
	                "areaType": "1",
	                "father": null,
	                "id": 30,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            },
	            {
	                "area": "新疆",
	                "areaID": "650000",
	                "areaType": "1",
	                "father": null,
	                "id": 31,
	                "isParent": false,
	                "lat": null,
	                "lng": null,
	                "parentName": null
	            }
	        ]
	    },
	    "success": true
	}